name: Issue Summarizer

on:
  issues:
    types:
      - closed

jobs:
  trigger-hypermode:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hypermode Function
        run: |
          curl -X POST http://localhost:8686/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.HYPERMODE_API_KEY }}" \
          -d '{
            "query": "mutation($repo: String!, $issueNumber: Int!, $title: String!, $body: String!) { 
              SimpleHandler(repo: $repo, issueNumber: $issueNumber, title: $title, body: $body) 
            }",
            "variables": {
              "repo": "${{ github.repository }}",
              "issueNumber": ${{ github.event.issue.number }},
              "title": "${{ github.event.issue.title }}",
              "body": "${{ github.event.issue.body }}"
            }
          }'
