name: Issue Summarizer

on:
  issues:
    types:
      - closed

jobs:
  trigger-hypermode:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hypermode Function
        run: |
          curl -X POST https://gh-issue-kb-steph-playground.hypermode.app/graphql \
          -H "Content-Type: application/json" \
          -d '{
            "query": "query { simpleHandler }"
          }'
