name: Issue Summarizer

on:
  issues:
    types:
      - closed

jobs:
  trigger-hypermode:
    runs-on: ubuntu-latest

    steps:
      - name: Log Inputs for Debugging
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Title: ${{ github.event.issue.title }}"
          echo "Body: ${{ github.event.issue.body }}"

      - name: Trigger Hypermode Function
        run: |
          curl -X POST https://gh-issue-kb-steph-playground.hypermode.app/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.HYPERMODE_API_KEY }}" \
          --data-raw '{
            "query": "query($repo: String!, $issueNumber: Int!, $title: String!, $body: String!) { 
              simpleHandler(repo: $repo, issueNumber: $issueNumber, title: $title, body: $body) 
            }",
            "variables": {
              "repo": "'"${{ github.repository }}"'",
              "issueNumber": '"${{ github.event.issue.number }}"',
              "title": "'"${{ github.event.issue.title }}"'",
              "body": "'"${{ github.event.issue.body }}"'"
            }
          }'
