name: Issue Summarizer

on:
  issues:
    types:
      - closed

jobs:
  trigger-hypermode:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Hypermode Function
        run: |
          curl -X POST https://gh-issue-kb-steph-playground.hypermode.app/graphql \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.HYPERMODE_API_KEY }}" \
          -d '{
            "query": "query { issueClosedHandler(repo: \"${{ github.repository }}\", issueNumber: ${{ github.event.issue.number }}, title: \"${{ github.event.issue.title }}\", body: \"${{ github.event.issue.body }}\") }"
          }'
